baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

relativeURLs = true

# Generate robots.txt
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[markup.goldmark.renderer]
unsafe = true

[params]
hideMadeWithLine = true
hideRSSLink = false
math = true
contactEmail = "nobody@example.com"
paletteA = "#ffffff"
paletteB = "#ffffff"
paletteC = "#000000"
paletteD = "#76a048"
paletteE = "#e982b6"
paletteF = "#333333"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
